config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :posts do
    resources :comments, except: :show
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true

  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :set_comment, only: [:edit, :update, :destroy]

  def index
    @comments = @post.comments
  end

  def new
    @comment = @post.comments.build
  end

  def create
    @comment = @post.comments.build(comment_params)
    if @comment.save
      flash[:notice] = 'Comment created successfully'
      redirect_to post_comments_path(@post)
    else
      render :new
    end
  end
  def edit; end

  def update
    if @comment.update(comment_params)
      flash[:notice] = 'Comment updated successfully'
      redirect_to post_comments_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    flash[:notice] = 'Comment deleted successfully'
    redirect_to post_comments_path(@post)
  end

  private

  def set_post
    @post = Post.find params[:post_id]
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_comment
    @comment = @post.comments.find(params[:id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :set_post, only: [:show, :edit, :update, :destroy]
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    # render json: params

    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = 'Post created successfully'
      redirect_to posts_path
    else
      flash.now[:alert] = 'Post create failed'
      render :new, status: :unprocessable_entity
    end
  end

  def show; end

  def edit; end

  def update
    if @post.update(post_params)
      flash[:notice] = 'Post updated successfully'
      redirect_to posts_path
    else
      flash.now[:alert] = 'Post update failed'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy

    @post.destroy
    flash[:notice] = 'Post destroyed successfully'
    redirect_to posts_path
  end


  private

   def set_post
     @post = Post.find(params[:id])
   end

  def post_params
      params.require(:post).permit(:title, :content)
  end



end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_form.html.erb
<%= form_with model: comment, url: path, data: { turbo: false } do |form| %>
  <% if comment.errors.any? %>
    <ul>
      <% comment.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  <% end %>
  <div>
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>

app/views/comments/edit.html.erb
<h1>Title: <%= @post.title %></h1>
<h2>Edit Comment ID: <%= @comment.id %></h2>
<%= render partial: 'form', locals: { post: @post, comment: @comment, path: post_comment_path(@post, @comment) } %>

app/views/comments/index.html.erb
<h2>Comments</h2>
<ul>
  <% @comments.each do |comment| %>

    <li>
      <%= comment.content %>(<%= comment.created_at %>)
      <%= link_to 'Edit', edit_post_comment_path(@post, comment) %>
      <%= button_to 'Delete', post_comment_path(@post, comment), method: :delete %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <% if flash[:notice] %>
        <p class="notice"><%= notice %></p>
       <% end %>
     <% if flash[:alert] %>
         <p class="alert"><%= alert %></p>
       <% end %>
  <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: post do |form| %>
  <% if post.errors.any? %>
    <ul>
      <% post.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  <% end %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post id: <%= @post.id %></h1>
<%# if @post.errors.any? %>
<!--  <ul>-->
    <%# @post.errors.each do |error| %>
<!--      <li><%#= error.full_message %></li>-->
    <%# end %>
<!--  </ul>-->
<%# end %>
<%#= form_with model: @post do |form| %>
<!--  <div>-->
    <%#= form.label :title %>
    <%#= form.text_field :title %>
<!--  </div>-->
<!--  <div>-->
    <%#= form.label :content %>
    <%#= form.text_field :content %>
<!--  </div>-->
  <%#= form.submit %>


<%# end %>

<%= render partial: 'form', locals: { post: @post } %>
<%= link_to 'Index', posts_path %>

app/views/posts/index.html.erb
<h1>Post List</h1>

<table>
  <thead>
  <td>title</td>
  <td>content</td>
  <td>action</td>
  </thead>
  <%= link_to 'New', new_post_path %>
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.content %></td>
      <td></td>
      <td>
        <%= link_to 'Show', post_path(post) %>
        <%= link_to 'Edit', edit_post_path(post) %>
        <%= button_to 'Delete', post_path(post), method: :delete %>
        <%= link_to 'Comments', post_comments_path(post) %>
        <%= link_to 'New Comment', new_post_comment_path(post) %>
      </td>
    </tr>
  <% end %>
  <%= link_to 'Post List', posts_path %>
</table>

app/views/posts/show.html.erb
<h1>show post id: <%= @post.id %></h1>
<ul>
  <li><%= @post.title %></li>
  <li><%= @post.content %></li>
</ul>

<%= link_to 'Index', posts_path %>

app/views/welcome/index.html.erb
<h1>Hello World!</h1>
<p>Welcome to my page!</p>